### ISSUE TITLE
Feature request - Obtaining information

### ISSUE THREAD

**Issue by NorthCam18** [KDani-99/FivePD-API#1]
Something that would be useful is a method to obtain information on a ped, such as their name/address. That as well as information about a vehicle, such as owner, plate and such. Not sure if information is randomly generated now or such, but could be very useful to use in callouts.

**Comment by KDani-99** [comment]
In the next API update, you'll be able to obtain information about the ped, including:
Ability to:
- set items
- get every data 
- set/get whether the ped is intoxicated
(More details will be written in the update notes)

**Comment by Squibsie** [comment]
> In the next API update, you'll be able to obtain information about the ped, including:
> Ability to:
> 
> * set items
> * get every data
> * set/get whether the ped is intoxicated
>   (More details will be written in the update notes)

Legend, I'm having a lot of fun making callouts at the moment!

**Comment by KDani-99** [comment]
Thank you for your contribution!

**Comment by KDani-99** [comment]
Closing the issue as these features will be available in the next version.
