### ISSUE TITLE
Callout requirements - only show a call when requirements are met

### ISSUE THREAD

**Issue by HB-2012** [KDani-99/FivePD-API#10]
As a callout developer I'd like to be able to set callout requirements. I'd like to prevent the callout from showing up at all when requirements are _not_ met.

Possible use cases:
* Only allow the callout to be shown when the time in game is between 9PM and 3AM.
* Only allow callout when ped skin is firefighter.
* Only allow callout when it is raining.

I think this can be done rather easily without breaking backwards compatibility too much. My suggestion would be to set a flag in the InitBase method which tells the CalloutManager if the script has been initialized and ready for use or not. If not, the CalloutManager should try a different callout.

**Comment by Squibsie** [comment]
To further this, the ability to detect what dept the player is? I get obviously the server admin defines department but if there was a way to set identifiers for a certain type of callout it'd be quite interesting.

For example, wildlife related calls would only spawn for Parks Officers, and highway obstructions would only come up for the highway patrol etc.

The only issue I see with this, is that is then limits customisation for players if you guys define a list of department types. I can only think that the addition of 'attributes' to each department would work as then a script author can simply state that for the callouts to spawn for a certain dept type, they must add a specific attribute to the dept in the MDT.

**Comment by KDani-99** [comment]
Great suggestions!
We will improve the api with these functionalities once we have a more stable version.
Thanks again.

**Comment by HB-2012** [comment]
> I can only think that the addition of 'attributes' to each department would work as then a script author can simply state that for the callouts to spawn for a certain dept type, they must add a specific attribute to the dept in the MDT.

I would think that allowing for a generalized way to check "requirements" to the call would also solve this issue, as then you'd be able to hook it up to a command that enables said calls. Or you could check the area and vehicle the player is in and the skin that the ped currently has.

Your suggestion works as well, but it sounds like a more difficult solution for the developers. Of course it isn't up to me, but that's just my 2 cents.

**Comment by Squibsie** [comment]
> > I can only think that the addition of 'attributes' to each department would work as then a script author can simply state that for the callouts to spawn for a certain dept type, they must add a specific attribute to the dept in the MDT.
> 
> I would think that allowing for a generalized way to check "requirements" to the call would also solve this issue, as then you'd be able to hook it up to a command that enables said calls. Or you could check the area and vehicle the player is in and the skin that the ped currently has.
> 
> Your suggestion works as well, but it sounds like a more difficult solution for the developers. Of course it isn't up to me, but that's just my 2 cents.

Yes, this might be true. My only thought is if people use EUP skins or custom vehicles that checking disappears. As people can set their dept names to anything they fancy, you can't even check the department name. As such, I thought having department attrubutes would work as the script writer can define that the 'beachpatrol' attribute is required and then the server admin can add that to the relevant department field so that the callout spawns.
Certainly isn't the cleanest, but its the best way I can think to maintain the high degree of customisation.

**Comment by KDani-99** [comment]
This feature will be available in API v0.6.4.
