### ISSUE TITLE
Call 'In Progress'

### ISSUE THREAD

**Issue by Squibsie** [KDani-99/FivePD-API#11]
I've not noted any clashes yet, so perhaps logic exists already. However it might be pertinent to have an identifier that allows you either set if a callout can be generated repeatedly, or block it from occurring if it's already in progress.
For calls with random locations, its fine if a callout is repeatedly generated for different players, however I have some more in-depth callouts where a static location is used, and in this instance, it'd be quite annoying if a second player has the same callout loaded for them halfway through our run-through of the call.

**Comment by KDani-99** [comment]
Yes, thats the exact idea how we want to solve this issue.
Thank you!

**Comment by KDani-99** [comment]
API v0.6.4 will require a GUID to prevent FixedLocation calls being spawned at the same location.
Thanks again!
