### ISSUE TITLE
Adding functionality make extensions for FivePD

### ISSUE THREAD

**Issue by AleksanderEvensen** [KDani-99/FivePD-API#12]
This came to mind when I tried to make my plugin turn on and off the "On duty" state. After digging in the code I saw that you had tons of EventHandlers for handling custom events. I hope that you could add functionality to use events to control parts of FivePD. It would also be interesting if we could add listeners and retrieve data, like what mission you're on, when a mission is completed, etc..

**Comment by KDani-99** [comment]
We'll try adding that.
Thanks!

**Comment by Flambe** [comment]
Yeah I'd love to be able to hook/listen into the fivepd events so I can push them somewhere else, e.g. a discord channel.

There are already some events there, but additional ones like OnReportCreated etc would be really useful

**Comment by KDani-99** [comment]
Thank you! Will definitely add more events in future updates.

**Comment by KDani-99** [comment]
There'll be more, but for now, here's the first that you can use:
https://github.com/KDani-99/FivePD-API/wiki/API-v0.6.4---Update#getplayerdata-event
