### ISSUE TITLE
Set Ped Identity 

### ISSUE THREAD

**Issue by Squibsie** [KDani-99/FivePD-API#13]
In order to increase uniformity, the ability to modify elements of the Ped identity would be nice.

For instance, being able to set if a ped has a warrant when you spawn them in your callouts.

Further to this, specifying what they have in their inventory too, this would lead to players having to search suspects to see if they have drugs etc.

**Comment by KDani-99** [comment]
https://github.com/KDani-99/FivePD-API/issues/1
