### ISSUE TITLE
Thoughts about open-source?

### ISSUE THREAD

**Issue by AleksanderEvensen** [KDani-99/FivePD-API#14]
What are your thoughts about open-source, and community contributions to the code base?

**Comment by AleksanderEvensen** [comment]
I would like to contribute to the Cruise Control code, to prevent flying with cars.

Cancel the cruise control when the vehicle is in the air.

**Comment by KDani-99** [comment]
We don't plan to go open-source as of yet.
If you'd like to help us, you can reach us out on Discord.
Add **Natixco#9676** for cruise control contribution, or me **Daniel K.#9648** for other API related questions.
Thank you!
