### ISSUE TITLE
Improved date/time handling

### ISSUE THREAD

**Issue by Flambe** [KDani-99/FivePD-API#17]
I'm currently making a discord bot that reads reports and other things from the FivePD DB. From the looks of it, you store the date and time in the players timezone in the DB? This makes it awkward for me to handle as many of us are in different timezones, and therefore I can't easily convert it without knowing them all first.

Would it be possible to store all dates/times in a fixed timezone (e.g. UTC), or store the users timezones as well?

**Comment by Flambe** [comment]
Looked into it a bit more and it looks like a lot of the dates are configurable, but you do store unix timestamps in some tables. Would it be possible to store a unix timestamp in each table?

**Comment by KDani-99** [comment]
Yes, I'll change that to be server-sided and I'll add unix timestamp to each table (already wanted to add it to set up n system that deletes reports after a certain amount of time).
Thank you!

**Comment by KDani-99** [comment]
After thinking about it for a while, we have decided not to add a timestamp field to each table. If you wish to develop addons that would use a timestamp, you can provide an installation guide with your addon to inform clients to manually add the timestamp field to their tables.
Sorry for the (very) late response.
