### ISSUE TITLE
FivePD API Suggestions.

### ISSUE THREAD

**Issue by xDman2000** [KDani-99/FivePD-API#18]
The current API is amazing if matched well with the Native FiveM functions, but I think it could go a long way if some additional events are added in.

Suggestions:
1. OnLoad() - Could be an event that gets executed when FivePD Loads in your callout, so we can preload needed stuff from config files etc and don't have to read the config files everytime the Callout is getting initialized.
2. PedOnDeath() - Not sure if this can be done inside FivePD or rather a FiveM issue but gonna put it here anyway, would be nice to execute something when a specific Ped Dies (For example a victim in a callout) rather then having to put a "while(ped.IsAlive) { BaseScript.Delay(100) }" combo in your code.
3. PedOnRevive() - Again unsure if this is a FivePD or FiveM thing, but it would be nice if we get "notified" when for example a called EMS can revive someone. So the Ped is not just dumbfounded and standing in the middle of the roads.
4. PedGotArrested() - Speaks for itself but it would be nice to have an event when a ped gets arrested.
5. Some kind of way of setting an objective for a player or ending a call with a function, for example if a specific ped gets arrested the call should end with Code 4, so people don't have to end calls manually all the time.

Not event related stuff:
- Having some sort of access to the top left 911 call indicator, so people could change what is being written out instead of the default "Responding", status. Would be fun to redo them like "En Route to Scene", "On Scene", "In Pursuit" or whatever people wanna put out there.
- Would be nice to get some sort of menu inside callouts so for example in a suicide situation an Officers could try to talk down the suspect from jumping, and based on the officers question the subject could decide about the sucide..

These are the ones I could currently think of.

**Comment by xDman2000** [comment]
+1 Addition, would be nice to be able to check what Police department the player is in, so we could assign calls according to it. Like if he joinst LS Coast Guards, then I can assign boat callouts to him.
+2 And the overall capeabilty to assign callouts to specific departments/areas or smth like that.

**Comment by KDani-99** [comment]
Your first suggestions will be in a later update (not in 0.6.4), but the other will be in the next version. You'll be able to obtain information about the player (eg. Rank, Department, DepartmentID, XP, DisplayName, and a few more ).
TIll I don't add the first suggestions, I'll leave this issue open.
Thank you!

**Comment by KDani-99** [comment]
Most of these will be in the next version of the API.
Thanks.
