### ISSUE TITLE
distance checking

### ISSUE THREAD

**Issue by Squibsie** [KDani-99/FivePD-API#19]
Perhaps a nicety, but clearly FivePD has distance checking built in as this how the callouts are triggered. As you will likely know, checking the distance between player and call is a bit clunky if you are to write your own stuff.
Would it be possible for the API to expose the use of that distance checking method? Just to save duplicitous code.

**Comment by KDani-99** [comment]
Sorry, but I don't really understand it, what would you like to achieve?

**Comment by HB-2012** [comment]
Not sure if you know about the existance of `World.GetDistance`, but perhaps that might be of use.
