### ISSUE TITLE
api ideas

### ISSUE THREAD

**Issue by Directorhappy** [KDani-99/FivePD-API#22]
make a resource or something along the lines to link to a discord so that we can see active calls and the officers that accept calls and maybe show the call information

**Comment by KDani-99** [comment]
Will look into it. 
Thanks!

**Comment by kpham0** [comment]
> make a resource or something along the lines to link to a discord so that we can see active calls and the officers that accept calls and maybe show the call information

like a Discord bot or Rich Presence?

**Comment by Directorhappy** [comment]
No like it sebds call to the discors kinda like external dispatch as well as 911 call monitor something so people can see the call your takeing

Sent from my Sprint Samsung Galaxy Note10+.

________________________________

**Comment by kpham0** [comment]
"911 call monitor" - This would require some sort of CAD system. I'm guessing there would be a designated dispatcher or group of dispatchers. I've been looking into getting a simple CAD system setup on my test server.
This could also have some sort of webhook which can send a chat message to a specific Discord channel ("Sends call to discord").

**Comment by Directorhappy** [comment]
N5PD there is a cat they're Built-in to the framework is there a way to use that to make of the Web hook to talk to a discord server

Sent from my Sprint Samsung Galaxy Note10+.

________________________________

**Comment by Directorhappy** [comment]
In fivepd there is a cad and mdt system

Sent from my Sprint Samsung Galaxy Note10+.

________________________________

**Comment by kpham0** [comment]
doh you're right. For some reason I'm thinking FiveM (vanilla).

**Comment by michaelcerne** [comment]
Could also do something with the rich presence join system ("join the player's active callout as backup"), but that's probably beyond the scope of the API. Just a thought.

**Comment by ToxicRageTv** [comment]
I was working on an FD version of FivePD and was using discord webhooks and a bot I made to display info when the user accepted a call. I feel like this could be a very cool addition to FivePD. Also some way to access the info for the call the user is on would be cool too.
![Annotation 2020-06-08 161540](https://user-images.githubusercontent.com/60159580/84089256-52ac2c00-a9a3-11ea-92e9-f78d926e9d91.png)

**Comment by KDani-99** [comment]
Yeah, itll be added.
