### ISSUE TITLE
Config Support into FivePD

### ISSUE THREAD

**Issue by xDman2000** [KDani-99/FivePD-API#23]
I think it would be really nice to have Config support in FivePD.

My suggestion on how you guys could do this the easiest way.
If you would include configs into the "__resource.lua" under files like
```
files{
   'callouts/*.json',
}
```
This would make so developers could use a FiveM native to access their files.
for example if I have my callout.dll named as "OfficerDown.net.dll" and I want a config file for it called "OfficerDown.json", I can access that file with the FiveM Native "0x76A9EE1F" the following way:
```csharp
string config = LoadResourceFile("fivepd", "callouts/OfficerDown.json");
```

So the .dll and the .json config files can be at the same place, and every developer can use their config files the way they want. :)

Ps.: Hopefully I wasn't too confusing.

**Comment by KDani-99** [comment]
Great suggestion! We'll add it in the next version.
Thank you!

**Comment by KDani-99** [comment]
It'll be in 1.0.6.
