### ISSUE TITLE
subject.NetworkID

### ISSUE THREAD

**Issue by Squibsie** [KDani-99/FivePD-API#24]
Not sure If i'm doing something incorrectly, but Visual Studio is throwing issues when I use the following:

`dynamic data = await this.GetPedData(subject.NetworkId);`

where subject is a spawned ped above. Newest API is referenced, but the VS advises "Ped does not contain a definition for Network ID' and asks if I am missing any references?

**Comment by KDani-99** [comment]
It is NetworkId (there might have been in typo in one of the wiki pages?)

**Comment by Squibsie** [comment]
I apologise, I did use lowercase, but still the same issue unless i've misunderstood the instantiation of peds?

**Comment by Squibsie** [comment]
My apologies, I'd gone down a rabbit hole and somehow was using an outdated version of CitizenFX.core - Now fixed, and not a FiveM/API issue.
