### ISSUE TITLE
Request to Force Callout

### ISSUE THREAD

**Issue by Rich-Dunne** [KDani-99/FivePD-API#26]
As an admin, I would like to be able to force callouts upon players.

**Comment by KDani-99** [comment]
So admins should be able to trigger a callout for players?

**Comment by Rich-Dunne** [comment]
Yes, similar to the Force Callout in the debug menu that you can do for yourself, I'd like to be able to select a player to force a callout upon.

**Comment by KDani-99** [comment]
It is more like a gameplay feature suggestion rather than API, someone has already made this on the fivepd forums a few days ago.
