### ISSUE TITLE
Automatically notify dept for backup

### ISSUE THREAD

**Issue by Squibsie** [KDani-99/FivePD-API#28]
Functionality to allow you as the callout developer to automatically notify people in a certain department for backup on a callout. This would be good for callouts where they are a major incident, or in cases where people make use of jurisdictions more and want to notify the local PD too. I.E Call based in Paleto Bay comes to BCSO, but on the acceptance of that call, it automatically calls any units in Paleto Bay Police Department as well.

**Comment by KDani-99** [comment]
I assume you want only the player's department to be notified about the callout, right?

**Comment by Squibsie** [comment]
To be honest, being able to specify the department name, or use the playerdata department object to acheive notifying their department would be preferable. That way you can get a call in the National Park area as LSPD, but also notify players in the SAPR department to it too.

**Comment by Salzian** [comment]
Simply exposing the "Call Backup" functionality to the API would already be great.

**Comment by KDani-99** [comment]
Added in API v1.0.2.
