### ISSUE TITLE
Better error information for callout developers

### ISSUE THREAD

**Issue by HB-2012** [KDani-99/FivePD-API#31]
Right now, when you made a derp and the callout couldn't be loaded or initialized for some reason, a rather generic "The callout could not be accepted" error is shown. As a callout developer, that's pretty useless, seeing as we have no clue what actually happened or what is actually causing the error. I think not bothering the day-to-day FivePD users with stacktraces is a good thing, however, we have to strike a balance between end-users and developers.

It would be really nice if there was a little bit more information in said error. Perhaps even a stacktrace? I'm thinking of allowing a debug- or developer-mode through the FivePD settings file? Or as an option in the debug menu in FivePD?

**Comment by KDani-99** [comment]
Yeah, this has already been requested [here,](https://github.com/KDani-99/FivePD-API/issues/30).
It'll be added in the next version. However, you can just use try catch in your code and print out the error.
