### ISSUE TITLE
Callouts For Multiple Players

### ISSUE THREAD

**Issue by mc22697** [KDani-99/FivePD-API#39]
Custom (and possibly in game default) callouts have trouble with blips and backup requests. If a second player accepts the backup request for a callout they receive the "Marker" blip leading to the start location, but do not receive additional blips related to the task. For example in a street racing callout (https://gtapolicemods.com/index.php?/files/file/820-fivepd-street-race-callout/) the initial accepting player can see all blips for the racers, but a backup player can't see any of the racer blips, but only the initial yellow start blip. Is there a way to add this functionality in custom callouts?

**Comment by KDani-99** [comment]
A few parts of the callouts are not synced between players yet, but we'll try to support server-side code for such scenarios.
Thanks.

**Comment by KDani-99** [comment]
New API methods will be available in the next version to sync blips (automatically/manually).
Thanks for the suggestion!
