### ISSUE TITLE
Overridable OnStart(Ped closest) not found when relacing downloaded CitizenFX.Core with nuget CitizenFX.Core.Client

### ISSUE THREAD

**Issue by Salzian** [KDani-99/FivePD-API#40]
I tried replacing the CitizenFX.Core dependency with the [official nuget package of CitizenFX.Core.Client](https://www.nuget.org/packages/CitizenFX.Core.Client). However, after replacing I get an error that the overridable method `OnStart(Ped closest)` was not found.

The nuget package is up-to-date and seems to be identical to the downloadable dll of the FiveM client. Without insight into the FivePD source I cannot tell what dependency may break here.

This may not be a high priority but with the possible implementation of #36 and automated builds via GitHub actions, this would be a nice addition to the QoL development of FivePD addons.

**Comment by KDani-99** [comment]
Looks like CitizenFX.Core and CitizenFX.Core.Client are different.
I sent you a screenshot in the API Discord.

**Comment by KDani-99** [comment]
As @HB-2012 suggested, building against the nuget package seems to solve the issue.
I'll upload both from the next API version.
Thank you guys!

**Comment by Salzian** [comment]
Also it seems that aliases for nuget packages will soon be implemented: https://github.com/NuGet/Home/issues/4989
