### ISSUE TITLE
Expose Arrested Event

### ISSUE THREAD

**Issue by joshleaver** [KDani-99/FivePD-API#51]
are we able to expose an event when the player takes someone that was arrested to the jail icon or when they are transported via transport unit?

**Comment by KDani-99** [comment]
It is currently not possible.  
Would there be any use of it?

**Comment by joshleaver** [comment]
im working on a statistics dashboard and it would be easier if i can do it via an api and just increase in the db

**Comment by KDani-99** [comment]
Alright, it'll be available in the next API update (v1.1.1.0).
