### ISSUE TITLE
Duty Notification

### ISSUE THREAD

**Issue by BryanHendriks** [KDani-99/FivePD-API#53]
Would it be possible to incorporate in the configs, the ability to toggle the duty notification to all players. I have an RP server gathering traction and we would like to use fivepd for our emergency services while using ESX for our Civilians, our problem is that when someone goes on duty it notifies everyone, ruining roleplay. It would be nice to be able to turn it off so your crims dont hide when someone shows on duty. Thx in advance.

**Comment by natixco** [comment]
This is not API related. For the mod itself, you can make suggestions [here](https://gtapolicemods.com/index.php?/fivepd-suggestions/).
