### ISSUE TITLE
Update player data method

### ISSUE THREAD

**Issue by XJMLN** [KDani-99/FivePD-API#54]
Could we get a method to update player data (like rank, department etc.)? 
Right now when we make change to player in database from plugin it's not updating in game.

**Comment by KDani-99** [comment]
We'll implement these features (or similar) in the next API version.
Thanks for the suggestion!

**Comment by KDani-99** [comment]
This feature is now available in the dev branch. You can take a look how it'll work [here](https://github.com/KDani-99/FivePD-API/commit/09904d57ef13695b6137bc04fa6b722012ad59b7).

It'll be compatible with the next FivePD version.
