### ISSUE TITLE
Reckless Driver/GTA

### ISSUE THREAD

**Issue by WhaleHawkGaming** [KDani-99/FivePD-API#7]
Would be nice to have a reckless driver call or GTA call that leads into a pursuit

**Comment by Havok66** [comment]
This seems more so a Callout request than an API feature. 
There are a few Callouts already available on the FivePD downloads that should scratch this itch for you. I believe Timewinter6001/Jacob's Callouts has a reckless driver Callout.

**Comment by KDani-99** [comment]
It is not API related.
