### ISSUE TITLE
Pursuit - Request

### ISSUE THREAD

**Issue by BGHDDevelopment** [KDani-99/FivePD-API#8]
Hey! It would be amazing if we can have the option to make a car automatically flee once the player get’s into range. 

Example: In my newest callout pack I have a pursuit of armed suspects. Right now I have them manually speeding and driving away from the player though FivePD does not think the players pursuing them. So an option to make the player in pursuit on arrival would be amazing.

**Comment by KDani-99** [comment]
We'll be looking into it. Thanks.

**Comment by KDani-99** [comment]
Will be in API 0.6.5
